//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMCSoft.Core.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblException
    {
        public long ExceptionId { get; set; }
        public string MachineName { get; set; }
        public string MachinUser { get; set; }
        public string IpAddress { get; set; }
        public string UserAgentInfo { get; set; }
        public string LoginId { get; set; }
        public string TimeZone { get; set; }
        public string Culture { get; set; }
        public string URL { get; set; }
        public string Message { get; set; }
        public string Source { get; set; }
        public string StackTrace { get; set; }
        public string Info { get; set; }
        public Nullable<long> OccuredBy { get; set; }
        public System.DateTime OccuredOn { get; set; }
    }
}
